# BASE UI
ColorColumn: 'red'
Conceal: 'debug'
Cursor: 'red'
CursorIM: 'debug'
CursorColumn: 'blue red buri'
CursorLine: '- currentLine'
Directory: 'red'
DiffAdd: 'red'
DiffChange: 'red'
DiffDelete: 'red'
DiffText: 'red'
ErrorMsg: 'red'
VertSplit: 'cyan'
Folded: 'red'
FoldColumn: 'red'
SignColumn: 'red'
IncSearch: 'red'
LineNr: 'red'
MatchParen: 'red'
ModeMsg: 'red'
MoreMsg: 'red'
NonText: 'red'
Normal: 'cyan'
PMenu: 'red'
PMenuSel: 'red'
PmenuSbar: 'red'
PmenuThumb: 'red'
Question: 'red'
Search: 'red'
SpecialKey: 'red'
SpellBad: 'red'
SpellLocal: 'red'
SpellCap: 'red'
SpellRare: 'red'
StatusLine: 'red'
StatusLineNC: 'red'
TabLine: 'red'
TabLineFill: 'red'
TabLineSel: 'red'
Title: 'red'
Visual: 'black red'
VisualNOS: 'red'
WarningMsg: 'red'
WildMenu: 'red'
# BASE SYNTAX
Comment: 'grey'
Constant: 'red'
String: 'blue'
Character: 'red'
Boolean: 'magenta'
Number: 'magenta'
Float: 'magenta'
Identifier: 'red'
Function: 'red'
Statement: 'red'
Conditional: 'red'
Repeat: 'red'
Label: 'red'
Operator: 'red'
Keyword: 'red'
Exception: 'red'
PreProc: 'red'
Include: 'red'
Define: 'red'
Macro: 'red'
PreCondit: 'red'
Type: 'red'
StorageClass: 'red'
Structure: 'red'
Typedef: 'red'
Special: 'red'
SpecialChar: 'red'
Tag: 'red'
Delimiter: 'red'
SpecialComment: 'red'
Debug: 'red'
Underlined: 'red'
Ignore: 'red'
Error: 'red'
Todo: 'red'
