# BASE UI
ColorColumn: 'red'
Conceal: 'debug'
Cursor: 'red'
CursorIM: 'debug'
CursorColumn: 'blue red buri'
CursorLine: '- currentLine'
Directory: 'red'
DiffAdd: 'red'
DiffChange: 'red'
DiffDelete: 'red'
DiffText: 'red'
ErrorMsg: 'red'
VertSplit: 'currentLine'
Folded: 'red'
FoldColumn: 'red'
SignColumn: 'red'
IncSearch: '- yellow'
LineNr: 'yellow'
MatchParen: 'red'
ModeMsg: 'red'
MoreMsg: 'red'
NonText: 'tabChar'
Normal: 'white'
PMenu: 'red'
PMenuSel: 'red'
PmenuSbar: 'red'
PmenuThumb: 'red'
Question: 'red'
Search: '- yellow'
SpecialKey: 'red'
SpellBad: 'red'
SpellLocal: 'red'
SpellCap: 'red'
SpellRare: 'red'
StatusLine: 'red'
StatusLineNC: 'red'
TabLine: 'red'
TabLineFill: 'red'
TabLineSel: 'red'
Title: 'cyan'
Visual: '- grey1'
VisualNOS: 'red'
WarningMsg: 'red'
WildMenu: 'red'
# BASE SYNTAX
Comment: 'grey'
Constant: 'blue'
String: 'yellow'
Character: 'red'
Boolean: 'red'
Number: 'magenta'
Float: 'magenta'
Identifier: 'red'
Function: 'cyan'
Statement: 'magenta'
Conditional: 'cyan'
Repeat: 'red'
Label: 'red'
Operator: 'cyan'
Keyword: 'red'
Exception: 'red'
PreProc: 'red'
Include: 'blue'
Define: 'red'
Macro: 'red'
PreCondit: 'red'
Type: 'orange'
StorageClass: 'red'
Structure: 'red'
Typedef: 'red'
Special: 'red'
SpecialChar: 'red'
Tag: 'red'
Delimiter: 'red'
SpecialComment: 'red'
Debug: 'red'
Underlined: 'red'
Ignore: 'red'
Error: 'red'
Todo: 'red'
